<%@ Page Title="" Language="C#" MasterPageFile="~/MasterAnonymous.master" AutoEventWireup="true" CodeFile="HomePage.aspx.cs" Inherits="HomePage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div id="services" style="padding: 0px 50px 0px 0px; margin: 0px; color: rgb(0, 0, 0); font-family: verdana, lucida, arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(233, 233, 233);">
    <h3 style="padding: 0px; margin: 0px 0px 10px; height: 20px; width: 400px; background-color: rgb(19, 149, 202); color: rgb(255, 255, 255); border-bottom: 1px solid rgb(18, 137, 166); border-right: 20px solid rgb(18, 137, 166);"><span style="padding: 0px; margin: 0px;">Services</span></h3>
    <p class="p1" style="padding: 0px; margin: 0px 0px 10px; line-height: 19px; font-size: 12.8px; color: rgb(0, 0, 0);">
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet<span class="Apple-converted-space">&nbsp;</span><a href="#" style="padding: 0px; margin: 0px; color: rgb(0, 153, 153); text-decoration: none; font-weight: bold;">clita kasd gubergren, no sea takimata</a><span class="Apple-converted-space">&nbsp;</span>sanctus est Lorem ipsum dolor sit amet.</p>
    <p class="p2" style="padding: 0px; margin: 0px 0px 10px; line-height: 19px; font-size: 12.8px;">
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
    <p class="p3" style="padding: 0px; margin: 0px 0px 10px; line-height: 19px; font-size: 12.8px;">
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
</div>
<div id="support" style="padding: 0px 50px 0px 0px; margin: 0px; color: rgb(0, 0, 0); font-family: verdana, lucida, arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(233, 233, 233);">
    <h3 style="padding: 0px; margin: 0px 0px 10px; height: 20px; width: 400px; background-color: rgb(19, 149, 202); color: rgb(255, 255, 255); border-bottom: 1px solid rgb(18, 137, 166); border-right: 20px solid rgb(18, 137, 166);"><span style="padding: 0px; margin: 0px;">Support</span></h3>
    <p class="p1" style="padding: 0px; margin: 0px 0px 10px; line-height: 19px; font-size: 12.8px; color: rgb(0, 0, 0);">
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
</div>
<div id="development" style="padding: 0px 50px 0px 0px; margin: 0px; color: rgb(0, 0, 0); font-family: verdana, lucida, arial, helvetica, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(233, 233, 233);">
    <h3 style="padding: 0px; margin: 0px 0px 10px; height: 20px; width: 400px; background-color: rgb(19, 149, 202); color: rgb(255, 255, 255); border-bottom: 1px solid rgb(18, 137, 166); border-right: 20px solid rgb(18, 137, 166);"><span style="padding: 0px; margin: 0px;">Development</span></h3>
    <p class="p1" style="padding: 0px; margin: 0px 0px 10px; line-height: 19px; font-size: 12.8px; color: rgb(0, 0, 0);">
        Lorem ipsum dolor sit amet,<span class="Apple-converted-space">&nbsp;</span><a href="#" style="padding: 0px; margin: 0px; color: rgb(0, 153, 153); text-decoration: none; font-weight: bold;">consetetur sadipscing elitr, sed diam nonumy</a><span class="Apple-converted-space">&nbsp;</span>eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
    <p class="p2" style="padding: 0px; margin: 0px 0px 10px; line-height: 19px; font-size: 12.8px;">
        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
</div>
</asp:Content>

